// function women() {
//   window.location = "myntra-women.html";
// }
// function men() {
//   window.location = "myntra-men.html";
// }
function mainpage() {
  window.location = "myntra.html";
}
function men() {
  document.getElementById("maincontainer1").style.display = "block";
  // let mendiv = document.createElement("div");
  // mendiv.className = "menlist";
  // let menlista = document.createElement("div");
  // menlista.className = "menlista";
  // let menlistb = document.createElement("div");
  // menlistb.className = "menlistb";
  // let menlistc = document.createElement("div");
  // menlistc.className = "menlistc";
  // let menlistd = document.createElement("div");
  // menlistd.className = "menlistd";
  // let menliste = document.createElement("div");
  // menliste.className = "menliste";
  // let maincontainer = document.getElementById("maincontainer");
  // maincontainer.appendChild(mendiv);
  // mendiv.appendChild(menlista);
  // mendiv.appendChild(menlistb);
  // mendiv.appendChild(menlistc);
  // mendiv.appendChild(menlistd);
  // mendiv.appendChild(menliste);
  // let menheading1 = document.createElement("p");
  // menlista.appendChild(menheading1);
  // menheading1.className = "menlist-a-heading";
  // menheading1.innerHTML = "Topwear";
  // let topwearlistitem1 = document.createElement("a");
  // let topwearlistitem2 = document.createElement("a");
  // let topwearlistitem3 = document.createElement("a");
  // let topwearlistitem4 = document.createElement("a");
  // let topwearlistitem5 = document.createElement("a");
  // let topwearlistitem6 = document.createElement("a");
  // let topwearlistitem7 = document.createElement("a");
  // let topwearlistitem8 = document.createElement("a");
  // let topwearlistitem9 = document.createElement("a");
  // menlista.appendChild(topwearlistitem1);
  // menlista.appendChild(topwearlistitem2);
  // menlista.appendChild(topwearlistitem3);
  // menlista.appendChild(topwearlistitem4);
  // menlista.appendChild(topwearlistitem5);
  // menlista.appendChild(topwearlistitem6);
  // menlista.appendChild(topwearlistitem7);
  // menlista.appendChild(topwearlistitem8);
  // menlista.appendChild(topwearlistitem9);
  // topwearlistitem1.innerHTML = "T-Shirts";
  // topwearlistitem2.innerHTML = "Casual Shirts";
  // topwearlistitem3.innerHTML = "Formal Shirts";
  // topwearlistitem4.innerHTML = "Sweatshirts";
  // topwearlistitem5.innerHTML = "Sweaters";
  // topwearlistitem6.innerHTML = "Jackets";
  // topwearlistitem6.innerHTML = "Blazers & Coats";
  // topwearlistitem8.innerHTML = "Suits";
  // topwearlistitem9.innerHTML = "Rain-Jackets";
  // let hr = document.createElement("hr");
  // menlista.appendChild(hr);
  // let menheading2 = document.createElement("p");
  // menlista.appendChild(menheading2);
  // menheading2.className = "menlist-a-heading";
  // menheading2.innerHTML = "Indian & Festive Wear";
  // let indianwearlistitem1 = document.createElement("a");
  // let indianwearlistitem2 = document.createElement("a");
  // let indianwearlistitem3 = document.createElement("a");
  // let indianwearlistitem4 = document.createElement("a");
  // menlista.appendChild(indianwearlistitem1);
  // menlista.appendChild(indianwearlistitem2);
  // menlista.appendChild(indianwearlistitem3);
  // menlista.appendChild(indianwearlistitem4);
  // indianwearlistitem1.innerHTML = "Kurtas & KurtaSets";
  // indianwearlistitem2.innerHTML = "Sherwanis";
  // indianwearlistitem3.innerHTML = "Nehru Jackets";
  // indianwearlistitem4.innerHTML = "Dhotis";
  // let menheading3 = document.createElement("p");
  // menlistb.appendChild(menheading3);
  // menheading3.className = "menlist-a-heading";
  // menheading3.innerHTML = "Bottomwear";
  // let bottomwearlistitem1 = document.createElement("a");
  // let bottomwearlistitem2 = document.createElement("a");
  // let bottomwearlistitem3 = document.createElement("a");
  // let bottomwearlistitem4 = document.createElement("a");
  // let bottomwearlistitem5 = document.createElement("a");
  // menlistb.appendChild(bottomwearlistitem1);
  // menlistb.appendChild(bottomwearlistitem2);
  // menlistb.appendChild(bottomwearlistitem3);
  // menlistb.appendChild(bottomwearlistitem4);
  // menlistb.appendChild(bottomwearlistitem5);
  // bottomwearlistitem1.innerHTML = "Jeans";
  // bottomwearlistitem2.innerHTML = "Casual Trousers";
  // bottomwearlistitem3.innerHTML = "Formal Trousers";
  // bottomwearlistitem4.innerHTML = "Shorts";
  // bottomwearlistitem5.innerHTML = "Track Pants & Joggers";
  // let hr2 = document.createElement("hr");
  // menlistb.appendChild(hr2);
  // let menheading4 = document.createElement("p");
  // menlistb.appendChild(menheading4);
  // menheading4.className = "menlist-a-heading";
  // menheading4.innerHTML = "Innerwear & sleepwear";
  // let innerwearlistitem1 = document.createElement("a");
  // let innerwearlistitem2 = document.createElement("a");
  // let innerwearlistitem3 = document.createElement("a");
  // let innerwearlistitem4 = document.createElement("a");
  // let innerwearlistitem5 = document.createElement("a");
  // menlistb.appendChild(innerwearlistitem1);
  // menlistb.appendChild(innerwearlistitem2);
  // menlistb.appendChild(innerwearlistitem3);
  // menlistb.appendChild(innerwearlistitem4);
  // menlistb.appendChild(innerwearlistitem5);
  // innerwearlistitem1.innerHTML = "Brief & Trunks";
  // innerwearlistitem2.innerHTML = "Boxers";
  // innerwearlistitem3.innerHTML = "Vests";
  // innerwearlistitem4.innerHTML = "Sleepwear & Loungewear";
  // innerwearlistitem5.innerHTML = "Thermals";
  // let hr3 = document.createElement("hr");
  // menlistb.appendChild(hr3);
  // let menheading5 = document.createElement("p");
  // menlistb.appendChild(menheading5);
  // menheading5.className = "menlist-a-heading";
  // menheading5.innerHTML = "Plus-sizes";
  // let menheading6 = document.createElement("p");
  // menlistc.appendChild(menheading6);
  // menheading6.className = "menlist-a-heading";
  // menheading6.innerHTML = "Footwear";
  // let footwearlistitem1 = document.createElement("a");
  // let footwearlistitem2 = document.createElement("a");
  // let footwearlistitem3 = document.createElement("a");
  // let footwearlistitem4 = document.createElement("a");
  // let footwearlistitem5 = document.createElement("a");
  // let footwearlistitem6 = document.createElement("a");
  // let footwearlistitem7 = document.createElement("a");
  // menlistc.appendChild(footwearlistitem1);
  // menlistc.appendChild(footwearlistitem2);
  // menlistc.appendChild(footwearlistitem3);
  // menlistc.appendChild(footwearlistitem4);
  // menlistc.appendChild(footwearlistitem5);
  // menlistc.appendChild(footwearlistitem6);
  // menlistc.appendChild(footwearlistitem7);
  // footwearlistitem1.innerHTML = "Casual Shoes";
  // footwearlistitem2.innerHTML = "Sports Shoes";
  // footwearlistitem3.innerHTML = "Formal Shoes";
  // footwearlistitem4.innerHTML = "Sneakers";
  // footwearlistitem5.innerHTML = "Sandal & Floaters";
  // footwearlistitem6.innerHTML = "Flip Flpos";
  // footwearlistitem7.innerHTML = "Socks";
  // let hr4 = document.createElement("hr");
  // menlistc.appendChild(hr4);
  // let menheading7 = document.createElement("p");
  // menlistc.appendChild(menheading7);
  // menheading7.className = "menlist-a-heading";
  // menheading7.innerHTML = "Presonalcare & Grooming";
  // let menheading8 = document.createElement("p");
  // menlistc.appendChild(menheading8);
  // menheading8.className = "menlist-a-heading";
  // menheading8.innerHTML = "Sunglasses & Frames";
  // let menheading9 = document.createElement("p");
  // menlistc.appendChild(menheading9);
  // menheading9.className = "menlist-a-heading";
  // menheading9.innerHTML = "Watches";
  // let menheading10 = document.createElement("p");
  // menlistd.appendChild(menheading10);
  // menheading10.className = "menlist-a-heading";
  // menheading10.innerHTML = "Sports& Activewear";
  // let sportswearlistitem1 = document.createElement("a");
  // let sportswearlistitem2 = document.createElement("a");
  // let sportswearlistitem3 = document.createElement("a");
  // let sportswearlistitem4 = document.createElement("a");
  // let sportswearlistitem5 = document.createElement("a");
  // let sportswearlistitem6 = document.createElement("a");
  // let sportswearlistitem7 = document.createElement("a");
  // let sportswearlistitem8 = document.createElement("a");
  // let sportswearlistitem9 = document.createElement("a");
  // menlistd.appendChild(sportswearlistitem1);
  // menlistd.appendChild(sportswearlistitem2);
  // menlistd.appendChild(sportswearlistitem3);
  // menlistd.appendChild(sportswearlistitem4);
  // menlistd.appendChild(sportswearlistitem5);
  // menlistd.appendChild(sportswearlistitem6);
  // menlistd.appendChild(sportswearlistitem7);
  // menlistd.appendChild(sportswearlistitem8);
  // menlistd.appendChild(sportswearlistitem9);
  // sportswearlistitem1.innerHTML = "Sport Shoes";
  // sportswearlistitem2.innerHTML = "Sport Sandals";
  // sportswearlistitem3.innerHTML = "Formal Shirts";
  // sportswearlistitem4.innerHTML = "Active T-shirts";
  // sportswearlistitem5.innerHTML = "Track Pants & Shorts";
  // sportswearlistitem6.innerHTML = "Track Suits";
  // sportswearlistitem6.innerHTML = "Jackets & Sweatwear";
  // sportswearlistitem8.innerHTML = "Sport Accessories";
  // sportswearlistitem9.innerHTML = "Swimwear";
  // let hr5 = document.createElement("hr");
  // menlistd.appendChild(hr5);
  // let menheading11 = document.createElement("p");
  // menlistd.appendChild(menheading11);
  // menheading11.className = "menlist-a-heading";
  // menheading11.innerHTML = "Gadgets";
  // let gadgetslistitem1 = document.createElement("a");
  // let gadgetslistitem2 = document.createElement("a");
  // let gadgetslistitem3 = document.createElement("a");
  // let gadgetslistitem4 = document.createElement("a");
  // menlistd.appendChild(gadgetslistitem1);
  // menlistd.appendChild(gadgetslistitem2);
  // menlistd.appendChild(gadgetslistitem3);
  // menlistd.appendChild(gadgetslistitem4);
  // gadgetslistitem1.innerHTML = "SmartWearable";
  // gadgetslistitem2.innerHTML = "Fitness Gadgets";
  // gadgetslistitem3.innerHTML = "Headphones";
  // gadgetslistitem4.innerHTML = "Speaker";
  // let menheading12 = document.createElement("p");
  // menliste.appendChild(menheading12);
  // menheading12.className = "menlist-a-heading";
  // menheading12.innerHTML = "Fashion Accessories";
  // let fashionlistitem1 = document.createElement("a");
  // let fashionlistitem2 = document.createElement("a");
  // let fashionlistitem3 = document.createElement("a");
  // let fashionlistitem4 = document.createElement("a");
  // let fashionlistitem5 = document.createElement("a");
  // let fashionlistitem6 = document.createElement("a");
  // let fashionlistitem7 = document.createElement("a");
  // let fashionlistitem8 = document.createElement("a");
  // let fashionlistitem9 = document.createElement("a");
  // let fashionlistitem10 = document.createElement("a");
  // let fashionlistitem11 = document.createElement("a");
  // let fashionlistitem12 = document.createElement("a");
  // menliste.appendChild(fashionlistitem1);
  // menliste.appendChild(fashionlistitem2);
  // menliste.appendChild(fashionlistitem3);
  // menliste.appendChild(fashionlistitem4);
  // menliste.appendChild(fashionlistitem5);
  // menliste.appendChild(fashionlistitem6);
  // menliste.appendChild(fashionlistitem7);
  // menliste.appendChild(fashionlistitem8);
  // menliste.appendChild(fashionlistitem9);
  // menliste.appendChild(fashionlistitem10);
  // menliste.appendChild(fashionlistitem11);
  // menliste.appendChild(fashionlistitem12);
  // fashionlistitem1.innerHTML = "Wallets";
  // fashionlistitem2.innerHTML = "Belts";
  // fashionlistitem3.innerHTML = "Perfumes & Body Mists";
  // fashionlistitem4.innerHTML = "Trimmers";
  // fashionlistitem5.innerHTML = "Deodrans";
  // fashionlistitem6.innerHTML = "Ties,Cufflinks& Pocket Squares";
  // fashionlistitem6.innerHTML = " Giftsets";
  // fashionlistitem8.innerHTML = "Caps & Hats";
  // fashionlistitem9.innerHTML = "Mufflers";
  // fashionlistitem10.innerHTML = "Phone Cases";
  // fashionlistitem11.innerHTML = "Ring & Wristwear";
  // fashionlistitem12.innerHTML = "Helmets";
  // let hr6 = document.createElement("hr");
  // menliste.appendChild(hr6);
  // let menheading13 = document.createElement("p");
  // menliste.appendChild(menheading13);
  // menheading13.className = "menlist-a-heading";
  // menheading13.innerHTML = "Bags & Backpacks";
  // let menheading14 = document.createElement("p");
  // menliste.appendChild(menheading14);
  // menheading14.className = "menlist-a-heading";
  // menheading14.innerHTML = "Luggage & Trolleys";
  // // a.href = "";
}
function removemendiv() {
   document.getElementById("maincontainer1").style.display="none";
}
function women() {
  document.getElementById("maincontainer2").style.display="block"
  // let maincontainer = document.getElementById("maincontainer");
  // maincontainer.remove();
  // let womendiv = document.createElement("div");
  // womendiv.className = "womenlist";
  // let womenlista = document.createElement("div");
  // womenlista.className = "womenlista";
  // let womenlistb = document.createElement("div");
  // womenlistb.className = "womenlistb";
  // let womenlistc = document.createElement("div");
  // womenlistc.className = "womenlistc";
  // let womenlistd = document.createElement("div");
  // womenlistd.className = "womenlistd";
  // let womenliste = document.createElement("div");
  // womenliste.className = "womenliste";
  // let maincontainer2 = document.getElementById("maincontainer2");
  // maincontainer2.appendChild(womendiv);
  // womendiv.appendChild(womenlista);
  // womendiv.appendChild(womenlistb);
  // womendiv.appendChild(womenlistc);
  // womendiv.appendChild(womenlistd);
  // womendiv.appendChild(womenliste);
  // let womenheading1 = document.createElement("p");
  // womenlista.appendChild(womenheading1);
  // womenheading1.className = "womenlist-a-heading";
  // womenheading1.innerHTML = "Indian & Fusionwear";
  // let indianwearlistitem1 = document.createElement("a");
  // let indianwearlistitem2 = document.createElement("a");
  // let indianwearlistitem3 = document.createElement("a");
  // let indianwearlistitem4 = document.createElement("a");
  // let indianwearlistitem5 = document.createElement("a");
  // let indianwearlistitem6 = document.createElement("a");
  // let indianwearlistitem7 = document.createElement("a");
  // let indianwearlistitem8 = document.createElement("a");
  // let indianwearlistitem9 = document.createElement("a");
  // let indianwearlistitem10 = document.createElement("a");
  // womenlista.appendChild(indianwearlistitem1);
  // womenlista.appendChild(indianwearlistitem2);
  // womenlista.appendChild(indianwearlistitem3);
  // womenlista.appendChild(indianwearlistitem4);
  // womenlista.appendChild(indianwearlistitem5);
  // womenlista.appendChild(indianwearlistitem6);
  // womenlista.appendChild(indianwearlistitem7);
  // womenlista.appendChild(indianwearlistitem8);
  // womenlista.appendChild(indianwearlistitem9);
  // womenlista.appendChild(indianwearlistitem10);
  // indianwearlistitem1.innerHTML = "Kurta & Suites";
  // indianwearlistitem2.innerHTML = "Kurtis & Tops";
  // indianwearlistitem3.innerHTML = "Sarres";
  // indianwearlistitem4.innerHTML = "Ethnic Wear";
  // indianwearlistitem5.innerHTML = "Leggings,Salwar &Churidar";
  // indianwearlistitem6.innerHTML = "Skirts & Plazzo";
  // indianwearlistitem6.innerHTML = "Dress-Materials";
  // indianwearlistitem8.innerHTML = "Lehnga-Cholis";
  // indianwearlistitem9.innerHTML = "Dupattas & Shawl";
  // indianwearlistitem10.innerHTML = "Jackets";
  // let hr = document.createElement("hr");
  // womenlista.appendChild(hr);
  // let womenheading2 = document.createElement("p");
  // womenlista.appendChild(womenheading2);
  // womenheading2.className = "womenlist-a-heading";
  // womenheading2.innerHTML = "Belts,Scarves & More";
  // let womenheading3 = document.createElement("p");
  // womenlista.appendChild(womenheading3);
  // womenheading3.className = "womenlist-a-heading";
  // womenheading3.innerHTML = "Watches & Wearables";
  // let womenheading4 = document.createElement("p");
  // womenlistb.appendChild(womenheading4);
  // womenheading4.className = "womenlist-a-heading";
  // womenheading4.innerHTML = "Westernwear";
  // let westernwearlistitem1 = document.createElement("a");
  // let westernwearlistitem2 = document.createElement("a");
  // let westernwearlistitem3 = document.createElement("a");
  // let westernwearlistitem4 = document.createElement("a");
  // let westernwearlistitem5 = document.createElement("a");
  // let westernwearlistitem6 = document.createElement("a");
  // let westernwearlistitem7 = document.createElement("a");
  // let westernwearlistitem8 = document.createElement("a");
  // let westernwearlistitem9 = document.createElement("a");
  // let westernwearlistitem10 = document.createElement("a");
  // let westernwearlistitem11 = document.createElement("a");
  // let westernwearlistitem12 = document.createElement("a");
  // let westernwearlistitem13 = document.createElement("a");
  // womenlistb.appendChild(westernwearlistitem1);
  // womenlistb.appendChild(westernwearlistitem2);
  // womenlistb.appendChild(westernwearlistitem3);
  // womenlistb.appendChild(westernwearlistitem4);
  // womenlistb.appendChild(westernwearlistitem5);
  // womenlistb.appendChild(westernwearlistitem6);
  // womenlistb.appendChild(westernwearlistitem7);
  // womenlistb.appendChild(westernwearlistitem8);
  // womenlistb.appendChild(westernwearlistitem9);
  // womenlistb.appendChild(westernwearlistitem10);
  // womenlistb.appendChild(westernwearlistitem11);
  // womenlistb.appendChild(westernwearlistitem12);
  // womenlistb.appendChild(westernwearlistitem13);
  // westernwearlistitem1.innerHTML = "Dresses";
  // westernwearlistitem2.innerHTML = "T-shirts";
  // westernwearlistitem3.innerHTML = "Tops";
  // westernwearlistitem4.innerHTML = "Jeans";
  // westernwearlistitem5.innerHTML = "Trousers & Capris";
  // westernwearlistitem6.innerHTML = "Shorts & skirts";
  // westernwearlistitem7.innerHTML = "Co-Ords";
  // westernwearlistitem8.innerHTML = "Playsuites";
  // westernwearlistitem9.innerHTML = "JumpSuites";
  // westernwearlistitem10.innerHTML = "Shrugs";
  // westernwearlistitem11.innerHTML = "Shwetaer";
  // westernwearlistitem12.innerHTML = "Jackets & Coats";
  // westernwearlistitem13.innerHTML = "Blazers";
  // let hr2 = document.createElement("hr");
  // womenlistb.appendChild(hr2);
  // let womenheading5 = document.createElement("p");
  // womenlistb.appendChild(womenheading5);
  // womenheading5.className = "womenlist-a-heading";
  // womenheading5.innerHTML = "Plus Size";
  // let womenheading6 = document.createElement("p");
  // womenlistc.appendChild(womenheading6);
  // womenheading6.className = "womenlist-a-heading";
  // womenheading6.innerHTML = "Maternity";
  // let womenheading7 = document.createElement("p");
  // womenlistc.appendChild(womenheading7);
  // womenheading7.className = "womenlist-a-heading";
  // womenheading7.innerHTML = "Sunglasses& Frames";
  // let womenheading8 = document.createElement("p");
  // womenlistc.appendChild(womenheading8);
  // womenheading8.className = "womenlist-a-heading";
  // womenheading8.innerHTML = "Footwear";
  // let footwearlistitem1 = document.createElement("a");
  // let footwearlistitem2 = document.createElement("a");
  // let footwearlistitem3 = document.createElement("a");
  // let footwearlistitem4 = document.createElement("a");
  // let footwearlistitem5 = document.createElement("a");
  // let footwearlistitem6 = document.createElement("a");
  // let footwearlistitem7 = document.createElement("a");
  // womenlistc.appendChild(footwearlistitem1);
  // womenlistc.appendChild(footwearlistitem2);
  // womenlistc.appendChild(footwearlistitem3);
  // womenlistc.appendChild(footwearlistitem4);
  // womenlistc.appendChild(footwearlistitem5);
  // womenlistc.appendChild(footwearlistitem6);
  // womenlistc.appendChild(footwearlistitem7);
  // footwearlistitem1.innerHTML = "FLats";
  // footwearlistitem2.innerHTML = "Sports Shoes";
  // footwearlistitem3.innerHTML = "Formal Shoes";
  // footwearlistitem4.innerHTML = "Sneakers";
  // footwearlistitem5.innerHTML = "Heels";
  // footwearlistitem6.innerHTML = "Boots";
  // footwearlistitem7.innerHTML = "Socks";
  // let womenheading9 = document.createElement("p");
  // womenlistc.appendChild(womenheading9);
  // womenheading9.className = "womenlist-a-heading";
  // womenheading9.innerHTML = "Sports & Active wear";
  // let sportswearlistitem1 = document.createElement("a");
  // let sportswearlistitem2 = document.createElement("a");
  // let sportswearlistitem3 = document.createElement("a");
  // let sportswearlistitem4 = document.createElement("a");
  // let sportswearlistitem5 = document.createElement("a");
  // womenlistc.appendChild(sportswearlistitem1);
  // womenlistc.appendChild(sportswearlistitem2);
  // womenlistc.appendChild(sportswearlistitem3);
  // womenlistc.appendChild(sportswearlistitem4);
  // womenlistc.appendChild(sportswearlistitem5);
  // sportswearlistitem1.innerHTML = "FLats";
  // sportswearlistitem2.innerHTML = "Sports Shoes";
  // sportswearlistitem3.innerHTML = "Formal Shoes";
  // sportswearlistitem4.innerHTML = "Sneakers";
  // sportswearlistitem5.innerHTML = "Heels";
  // let womenheading10 = document.createElement("p");
  // womenlistd.appendChild(womenheading10);
  // womenheading10.className = "womenlist-a-heading";
  // womenheading10.innerHTML = " Lingerie & Sleepwear";
  // let sleepwearlistitem1 = document.createElement("a");
  // let sleepwearlistitem2 = document.createElement("a");
  // let sleepwearlistitem3 = document.createElement("a");
  // let sleepwearlistitem4 = document.createElement("a");
  // let sleepwearlistitem5 = document.createElement("a");
  // let sleepwearlistitem6 = document.createElement("a");
  // womenlistd.appendChild(sleepwearlistitem1);
  // womenlistd.appendChild(sleepwearlistitem2);
  // womenlistd.appendChild(sleepwearlistitem3);
  // womenlistd.appendChild(sleepwearlistitem4);
  // womenlistd.appendChild(sleepwearlistitem5);
  // womenlistd.appendChild(sleepwearlistitem6);
  // sleepwearlistitem1.innerHTML = "Bra";
  // sleepwearlistitem2.innerHTML = "Briefs";
  // sleepwearlistitem3.innerHTML = "Shapewear";
  // sleepwearlistitem4.innerHTML = "Sleepwear & Loungewear";
  // sleepwearlistitem5.innerHTML = "SwimWear";
  // sleepwearlistitem6.innerHTML = "Thermals";
  // let hr3 = document.createElement("hr");
  // womenlistd.appendChild(hr3);
  // let womenheading11 = document.createElement("p");
  // womenlistd.appendChild(womenheading11);
  // womenheading11.className = "womenlist-a-heading";
  // womenheading11.innerHTML = "Beauty & PersonalCare";
  // let beautylistitem1 = document.createElement("a");
  // let beautylistitem2 = document.createElement("a");
  // let beautylistitem3 = document.createElement("a");
  // let beautylistitem4 = document.createElement("a");
  // let beautylistitem5 = document.createElement("a");
  // let beautylistitem6 = document.createElement("a");
  // womenlistd.appendChild(beautylistitem1);
  // womenlistd.appendChild(beautylistitem2);
  // womenlistd.appendChild(beautylistitem3);
  // womenlistd.appendChild(beautylistitem4);
  // womenlistd.appendChild(beautylistitem5);
  // womenlistd.appendChild(beautylistitem6);
  // beautylistitem1.innerHTML = "Makeup";
  // beautylistitem2.innerHTML = "Skincare";
  // beautylistitem3.innerHTML = "Premium Beauty";
  // beautylistitem4.innerHTML = "Lipsticks";
  // beautylistitem5.innerHTML = "Fragrance";
  // beautylistitem6.innerHTML = "Personalcare";
  // let womenheading12 = document.createElement("p");
  // womenliste.appendChild(womenheading12);
  // womenheading12.className = "womenlist-a-heading";
  // womenheading12.innerHTML = "Gadgets";
  // let gadgetslistitem1 = document.createElement("a");
  // let gadgetslistitem2 = document.createElement("a");
  // let gadgetslistitem3 = document.createElement("a");
  // let gadgetslistitem4 = document.createElement("a");
  // womenliste.appendChild(gadgetslistitem1);
  // womenliste.appendChild(gadgetslistitem2);
  // womenliste.appendChild(gadgetslistitem3);
  // womenliste.appendChild(gadgetslistitem4);
  // gadgetslistitem1.innerHTML = "Smart Wearables";
  // gadgetslistitem2.innerHTML = "Spekar";
  // gadgetslistitem3.innerHTML = "Fitness gadgets";
  // gadgetslistitem4.innerHTML = "Headphones";
  // let hr4 = document.createElement("hr");
  // womenliste.appendChild(hr4);
  // let womenheading13 = document.createElement("p");
  // womenliste.appendChild(womenheading13);
  // womenheading13.className = "womenlist-a-heading";
  // womenheading13.innerHTML = "Jwellery";
  // let jwellerylistitem1 = document.createElement("a");
  // let jwellerylistitem2 = document.createElement("a");
  // let jwellerylistitem3 = document.createElement("a");
  // womenliste.appendChild(jwellerylistitem1);
  // womenliste.appendChild(jwellerylistitem2);
  // womenliste.appendChild(jwellerylistitem3);
  // jwellerylistitem1.innerHTML = "Fashion Jwellery";
  // jwellerylistitem2.innerHTML = "Fine Jwelleryr";
  // jwellerylistitem3.innerHTML = "Earingss";
  // let hr5 = document.createElement("hr");
  // womenliste.appendChild(hr5);
  // let womenheading14 = document.createElement("p");
  // womenliste.appendChild(womenheading14);
  // womenheading14.className = "womenlist-a-heading";
  // womenheading14.innerHTML = "Backpacks";
  // let womenheading15 = document.createElement("p");
  // womenliste.appendChild(womenheading15);
  // womenheading15.className = "womenlist-a-heading";
  // womenheading15.innerHTML = "Handbags,Bags & Wallet";
  // let womenheading16 = document.createElement("p");
  // womenliste.appendChild(womenheading16);
  // womenheading16.className = "womenlist-a-heading";
  // womenheading16.innerHTML = "Luggage & Trolleys";
}
function removewomendiv() {
 document.getElementById("maincontainer2").style.display="none";
}
function kids() {
  document.getElementById("maincontainer3").style.display = "block";
}
function removekidsdiv() {
  document.getElementById("maincontainer3").style.display = "none";
}
function home() {
  document.getElementById("maincontainer4").style.display = "block";
}
function removehomediv() {
  document.getElementById("maincontainer4").style.display = "none";
}